# 站点基础配置
title: "笔记"
description: "自用笔记"
baseurl: ""                # user.github.io 时留空
url: "https://illionj.github.io"

remote_theme: "pmarsceill/just-the-docs"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

navigation:
  - title: 首页
    url: /
  - title: 编程语言
    url: /categories/programming-languages/
  - title: 自动驾驶
    url: /categories/autonomous-driving/
  - title: 杂项
    url: /categories/miscellaneous/
  - title: 关于
    url: /about/

# 其他保持不变
collections:
  notes:
    output: true
    permalink: /notes/:path/

paginate: 5
paginate_path: "/page/:num/"
