# 站点基础配置
title: "笔记"
description: "自用笔记"
baseurl: ""                # user.github.io 时留空
url: "https://illionj.github.io"

remote_theme: "just-the-docs/just-the-docs@v0.6.2"   # 或最新稳定版
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# ———导航：默认隐藏所有页面———————————————
defaults:
  # ① 所有普通页面一律 nav_exclude: true
  - scope:
      path: ""            # 根目录下的所有文件
      type: "pages"
    values:
      nav_exclude: true

# ———可选：关闭自动生成的深层文件索引（建议保留搜索）———
# just_the_docs:
#   collections:
#     pages:
#       output: true
#       sidebar:
#         nav_exclude: true  # 0.5.0+ 新选项，只在最新版主题有效

# ———其它常规建议—————————
permalink: pretty          # 去掉 .html
paginate: 10               # 列表页每页 10 篇（若需要）
exclude: [Gemfile*, node_modules, vendor]
