# 站点基础配置
title: "笔记"
description: "自用笔记"
baseurl: ""                # user.github.io 时留空
url: "https://illionj.github.io"

# Remote theme 配置（Just the Docs）
remote_theme: "pmarsceill/just-the-docs"
plugins:
  - jekyll-remote-theme

# 导航栏
navigation:
  - title: 首页
    url: /
  - title: 笔记
    url: /notes/
  - title: 关于
    url: /about/

# 自定义集合：notes
collections:
  notes:
    output: true
    permalink: /notes/:path/

# 分页（Just the Docs 支持 jekyll-paginate）
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/page/:num/"
